language: node_js
script:
  - make build
  - make archive
deploy:
  provider: releases
  file: build/RindexDynamicValue.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
repo: coder4life/Paw-RindexDynamicValue